# As some repositories are using this action by referring to @master
# this branch needs to be kept alive until these references no longer exist.

name: Push almohad to dev
on:
  push:
    branches: almohad

jobs:
  push-to-dev:
    name: Push to dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
    - run: |
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git
        git push -f origin almohad:dev