# As some repositories are using this action by referring to @master
# this branch needs to be kept alive until these references no longer exist.

name: Push almohad to dev
on:
  push:
    branches: almohad

jobs:
  push-to-dev:
    name: Push to dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set environment variable "is-auto-commit"
    if: github.event.commits[0].message == env.CI_COMMIT_MESSAGE && github.event.commits[0].author.name == env.CI_COMMIT_AUTHOR
    run: echo "is-auto-commit=true" >> $GITHUB_ENV
    - run: |
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git
        git push -f origin almohad:dev