# As some repositories are using this action by referring to @master
# this branch needs to be kept alive until these references no longer exist.

name: Push almohad to dev
on:
  push:
    branches: almohad

jobs:
  push-to-dev:
    name: Push to dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        echo ${{ github.event.commits[0].message }}
        echo ${{ github.event.head_commit.message }}
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git
        git push -f origin almohad:dev
  
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: production-promotion