name: Create Auto PR on push to dev

on:
  push:
    branches:
      - dev

jobs:
  updateAuthor:
    runs-on: ubuntu@latest
    steps:
      - name: Checking out code
        uses: actions/checkout@master

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      
      - name: Update Author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "prod"
          base: dev
          title: "demo for auto pr"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body:
            THis is a pr to show auto creation
          token: ${{ secrets.TOKEN }}
          delete-branch: false