# As some repositories are using this action by referring to @master
# this branch needs to be kept alive until these references no longer exist.

name: Push almohad to dev
on:
  push:
    branches: almohad, dev

jobs:
  push-to-dev:
    name: Push to dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        echo ${{ github.event.commits[0].message }}
        echo ${{ github.event.head_commit.message }}
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git
        git push -f origin almohad:dev

# name: Create PR to main
# on:
#   push:
#     branches: dev

jobs:
  create-pull-request:
    name: PR to main
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@master

      - name: extracting commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: updating author info
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR