# As some repositories are using this action by referring to @master
# this branch needs to be kept alive until these references no longer exist.

name: Push almohad to dev
on:
  push:
    branches:
      - almohad

jobs:
  push-to-dev:
    name: Push to dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        echo ${{ github.event.commits[0].message }}
        echo ${{ github.event.head_commit.message }}
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git
        git push -f origin almohad:dev

  create-pull-request:
    name: PR to main
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@master

      - name: extracting commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: updating author info
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        run: peter-evans/create-pull-request@v3
        with:
          branch: "dev"
          base: main
          title: "PR MESSAGE HERE"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}
          body: This is to show automatic pr creation
          token: ${{ secrets.TOKEN }}
          delete-branch: false