name: Auto Pull Request (almohad)
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - almohad

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dev # The branch name where you want to push the assets
          FOLDER: dev # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Pushed from local machine: ({sha}) {msg}" # The commit message

      # - name: Creating Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     commit-message: Update report
      #     committer: GitHub <noreply@github.com>
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     signoff: false
      #     branch: example-patches
      #     delete-branch: true
      #     title: '[Example] Update report'
      #     body: |
      #       Update report
      #       - Updated with *today's* date
      #       - Auto-generated by [create-pull-request][1]

      #       [1]: https://github.com/peter-evans/create-pull-request
      #     labels: |
      #       report
      #       automated pr
      #     assignees: peter-evans
      #     reviewers: peter-evans
      #     team-reviewers: |
      #       owners
      #       maintainers
      #     milestone: 1
      #     draft: false




# push to master, main, develop
# pull request on main master